# Generated by Django 6.1.1 on 2026-09-14 10:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='service_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of the service/event'),
        ),
    ]
