# Generated by Django 6.1.1 on 2026-09-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_service_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteattachment',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
